apiVersion: v1
kind: Secret
metadata:
  name: {{ include "test.fullname" . }}-password
  labels:
    {{- include "test.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: "/abusetotal/kubernetes/secrets/argocd"
    avp.kubernetes.io/secret-version: "AWSCURRENT"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  password: <password>